---
# Horizontal Pod Autoscaler (optional but recommended for production)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: obo-app-hpa
  namespace: obo-ns
  labels:
    app: obo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: obo-app

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
